apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL3NtYXJ0b2ZmaWNlMy5rci5uY3IubnRydXNzLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogIjNRMENOTllxS2V4ZEVVczBneVcyIiwKICAgICAgInBhc3N3b3JkIjogIjV2dnBRYnRwTnJ0d2NQczE4aGh6c0FwdjRKWmlzTHpLUWVEeFdMTkQiCiAgICB9CiAgfQp9CiAg
kind: Secret
metadata:
  creationTimestamp: null
  name: nks-secret
  # namespace: {{ .Chart.Name }}
type: kubernetes.io/dockerconfigjson
