apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Chart.Name }}
data:
  nginx.conf: |
    server {
      listen       80;
      server_name  localhost;

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }
    }