apiVersion: v1
kind: Service
metadata:
  name: svc-mariadb
  # namespace: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: db
  clusterIP: 10.100.100.100
  ports:
  - port: 3306
    protocol: TCP 
    targetPort: 3306
