apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: nginx
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP 
    targetPort: 80
