apiVersion: v1
kind: Service
metadata:
  name: svc-mariadb
  namespace: {{ .Release.name }}
spec:
  type: NodePort
  selector:
    app: db
  ports:
  - port: 3306
    protocol: TCP 
    targetPort: 3306
    nodePort: 30000
