apiVersion: v1
kind: Service
metadata:
  name: svc-core
  # namespace: {{ .Chart.Name }}
spec:
  type: ClusterIP
  selector:
    app: core
  clusterIP: None
  ports:
  - name: restapi
    port: 10010
    protocol: TCP 
    targetPort: 10010
  - name: rsocket
    port: 10011
    protocol: TCP
    targetPort: 10011
