apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.layers.frontend.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        layer: frontend
    spec:
      nodeSelector:
        masterVersion: "{{ .Values.nodeSelector.masterVersion }}"
      affinity:
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: layer
                    operator: In
                    values:
                    - backend
                topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: v-html
        hostPath:
          path: {{ .Values.mountPaths.html }}
          type: DirectoryOrCreate
      containers:
      - name: nginx
        image: {{ .Values.layers.frontend.image.name }}:{{ .Values.layers.frontend.image.tag }}
        imagePullPolicy: {{ .Values.layers.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: {{ .Values.layers.frontend.resources.memory }}
            cpu: {{ .Values.layers.frontend.resources.cpu }}
          limits:
            memory: 1Gi
            cpu: 1
        volumeMounts:
        - name: v-html
          mountPath: /usr/share/nginx/html

