apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  # namespace: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.layers.frontend.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        layer: frontend
    spec:
      nodeSelector:
        masterVersion: "{{ .Values.nodeSelector.masterVersion }}"
      # affinity:
      #   podAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 100
      #         podAffinityTerm:
      #           labelSelector:
      #             matchExpressions:
      #             - key: layer
      #               operator: In
      #               values:
      #               - backend
      #           topologyKey: "kubernetes.io/hostname"
      volumes:
      - name: v-nginx-html
        hostPath:
          path: {{ .Values.mountPaths.html }}
      - name: v-nginx-config
        configMap:
          name: nginx-config
      containers:
      - name: nginx
        image: {{ .Values.layers.frontend.image.name }}:{{ .Values.layers.frontend.image.tag }}
        imagePullPolicy: {{ .Values.layers.frontend.image.pullPolicy }}
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 256Mi
            cpu: 200m
          limits:
            memory: 512Mi
            cpu: 400m
        volumeMounts:
        - name: v-nginx-html
          mountPath: /usr/share/nginx/html
        - name: v-nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf

