apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-smartoffice3
  namespace: {{ .Chart.Name }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.bodySize }}
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.api.path }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: svc-gateway
            port:
              number: 10000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-nginx
            port:
              number: 80
